# Generated by Django 5.2.8 on 2026-02-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид поручения')),
            ],
            options={
                'verbose_name': 'Вид поручения',
                'verbose_name_plural': 'Виды поручений',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Структурные подразделения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Номер документа')),
                ('base_document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Основание (номер документа)')),
                ('issue_date', models.DateField(verbose_name='Дата издания')),
                ('deadline', models.DateField(verbose_name='Срок исполнения')),
                ('description', models.TextField(verbose_name='Текст поручения')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Исполнено'), ('OVERDUE', 'Просрочено')], default='NEW', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approver', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'profile__is_approver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Визирующий')),
                ('controller', models.ForeignKey(limit_choices_to={'is_active': True, 'profile__is_controller': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to_control', to=settings.AUTH_USER_MODEL, verbose_name='Контролирующий')),
                ('executor', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to_execute', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_control.assignmenttype', verbose_name='Вид документа')),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('is_approver', models.BooleanField(default=False, verbose_name='Может быть визирующим')),
                ('is_controller', models.BooleanField(default=False, verbose_name='Может быть контролирующим')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_control.department', verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_control.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
