# Generated by Django 5.2.8 on 2026-02-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('is_approver', models.BooleanField(default=False, verbose_name='Может быть визирующим')),
                ('is_controller', models.BooleanField(default=False, verbose_name='Может быть контролирующим')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает (активен)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_control.department', verbose_name='Подразделение')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_control.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_approver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_to_approve', to='task_control.employee', verbose_name='Визирующий'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='controller',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_controller': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to_control', to='task_control.employee', verbose_name='Контролирующий'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='executor',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to_execute', to='task_control.employee', verbose_name='Исполнитель'),
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
