# Generated by Django 5.2.8 on 2026-02-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_control', '0002_employee_alter_assignment_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='telegram_id',
        ),
    ]
