# Generated by Django 5.2.8 on 2026-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_control', '0003_remove_employee_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_notified_created',
            field=models.BooleanField(default=False, verbose_name='Уведомление о создании отправлено'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_notified_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Последний срок, о котором уведомляли'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_reminded_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок, о котором уже было напоминание'),
        ),
    ]
