# Generated by Django 5.2.8 on 2026-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_control', '0004_assignment_is_notified_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='document_number',
            field=models.CharField(max_length=50, verbose_name='Номер документа'),
        ),
    ]
