# Generated by Django 5.2.8 on 2026-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_control', '0005_alter_assignment_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttype',
            name='color',
            field=models.CharField(blank=True, default='#6c757d', max_length=20),
        ),
    ]
