# Generated by Django 5.2.8 on 2026-02-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_control', '0003_remove_employee_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм (@username)')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя в TG')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия в TG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первого запуска (/start)')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to='task_control.employee', verbose_name='Сотрудник в базе')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
                'ordering': ['-created_at'],
            },
        ),
    ]
